name: Deploy application to ftp

on:
  workflow_dispatch:

jobs:
  deploy-to-ftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        uses: BrightSoftwares/infra-gh-actions/php-composer-dependencies@main
        with:
          appdir: /github/workspace/
          
      - name: Transferring application to VM via ftp
        uses: BrightSoftwares/infra-gh-actions/lftp-client@main
        with:
          USER: ${{ secrets.FTP_USER }}
          PASSWORD: ${{ secrets.FTP_PASSWORD }}
          HOST: ${{ secrets.FTP_HOST }}
          PUB_FTP_DIR: "/www/seven_alliances_wp/mytestfigapp"
          
